---
title: "Publications"
---
<head>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-ERV5WXQZ44"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-ERV5WXQZ44');
</script>
</head> 

### 2023

* Miguel Vallebueno-Estrada; Guillermo G. Hernández-Robles; Eduardo González-Orozco; **Iván López-Valdivia**; Teresa Rosales Tham; Víctor Vásquez Sánchez; Kelly Swarts; Tom D. Dillehay; Jean-Philippe Vielle-Calzada; Rafael Montiel. 2023. Domestication and lowland adaptation of coastal preceramic maize from Paredones, Peru. eLife, in press

### 2022

* **Lopez-Valdivia Ivan**, Alden Perkins, Hannah Schneider, Miguel Vallebueno-Estrada, James Burridge, Eduardo González-Orozco, Aurora Montufar, Rafael Montiel, Jonathan Lynch, Jean-Philippe Vielle-Calzada. 2022. Gradual domestication of root traits in the earliest maize from Tehuacan. PNAS Vol. 119 No. 17 e2110245119 [Full Record](https://www.pnas.org/doi/10.1073/pnas.2110245119)

### 2019

* **Lopez-Valdivia Ivan** (2019) Caracterización de raíces milenarias de maíz provenientes de Tehuacán: comparación con poblaciones actuales del género Zea. CINVESTAV. Mexico. Tesis de Maestria. [Full Record](LopezValdivia_master.pdf)

